In [4]:


import numpy as np



In [5]:
arr = np.zeros(10)
arr


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:


arr1 = np.ones(10)
arr1



array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
arr3 = np.ones(10)*3
arr3

arr3a = np.full((10),3)
arr3a


array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [8]:
arr4 = np.arange(20,40+1)
arr4


array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40])

In [9]:
arr5 = np.arange(20,41,2)
arr5

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [10]:
mat1 = np.array([[0,1,2], [3,4,5], [6,7,8]])
mat1


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
mat2 = np.eye(3)
mat2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
rand1 = np.random.random()
rand1


0.7004079563989931

In [13]:
rarr = np.random.random(20)
rarr

array([0.99712522, 0.86122572, 0.777962  , 0.16957239, 0.51324521,
       0.93522961, 0.47942471, 0.25875598, 0.39112291, 0.86372499,
       0.83401895, 0.46321916, 0.98775219, 0.70440037, 0.30445007,
       0.53510054, 0.38805082, 0.89303767, 0.51121867, 0.06551595])

In [14]:
mat = np.arange(25,50).reshape(5,5)
mat


array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [15]:
mat[1:4, 1:]


array([[31, 32, 33, 34],
       [36, 37, 38, 39],
       [41, 42, 43, 44]])